export const testMapJSON = {
    map: {
        src: "./Client/image/testRepeatGround.png",
        startPositionX: 0,
        startPositionY: 0,
        width: 100,
        height: 100,
        zIndex: 3,
        mapSizeX: 1000,
        mapSizeY: 1000,
        mapElement: {
            home3: {
                src: "./Client/image/treeTest.png",
                startPositionX: 3,
                startPositionY: 0,
                startPositionZ: -10,
                width: 5,
                height: 5,
                collaid: "./Client/image/collaid.png",
                colliderPositionX: 3,
                colliderPositionY:  0,
                colliderPositionZ: -10,
                colliderWidth: 5,
                colliderHeight: 2.5,
                zIndex: 1,
            },
            home2: {
                src: "./Client/image/treeTest.png",
                startPositionX: 0,
                startPositionY: 0,
                startPositionZ: -8,
                width: 5,
                height: 5,
                collaid: "./Client/image/collaid.png",
                colliderPositionX: 0,
                colliderPositionY:  0,
                colliderPositionZ: -8,
                colliderWidth: 5,
                colliderHeight: 2.5,
                zIndex: 1,
            },
            home4: {
                src: "./Client/image/treeTest.png",
                startPositionX: 0,
                startPositionY: 0,
                startPositionZ: 5,
                width: 10,
                height: 10,
                collaid: "./Client/image/collaid.png",
                colliderPositionX: 0,
                colliderPositionY:  0,
                colliderPositionZ: 5,
                colliderWidth: 10,
                colliderHeight: 2.5,
                zIndex: 1,
            },

            home5: {
                src: "./Client/image/treeTest.png",
                startPositionX: 0,
                startPositionY: 0,
                startPositionZ: 10,
                width: 15,
                height: 15,
                collaid: "./Client/image/collaid.png",
                colliderPositionX: 0,
                colliderPositionY:  0,
                colliderPositionZ: 10,
                colliderWidth: 15,
                colliderHeight: 2.5,
                zIndex: 1,
            },            /*home:{
                src: "./Client/image/midieval/archery_range.png",
                startPositionX: 15,
                startPositionY: -10,
                startPositionZ: 2,
                width: 15,
                height: 15,
                  collaid:"./Client/image/collaid.png",
                colliderPositionX: 15,
                colliderPositionY: -10,
                colliderPositionZ: 0,
                colliderWidth: 10,
                colliderHeight: 10,
                zIndex:1,
            },
            home2:{
                src: "./Client/image/midieval/barracks.png",
                startPositionX: -20,
                startPositionY: 10,
                startPositionZ: 2,
                width: 15,
                height: 15,
                  collaid:"./Client/image/collaid.png",
                colliderPositionX: -18,
                colliderPositionY: 6,
                colliderPositionZ: 0,
                colliderWidth: 14,
                colliderHeight: 5,
                zIndex:1,
            },
            home3:{
                src: "./Client/image/midieval/castle.png",
                startPositionX: 0,
                startPositionY: 12,
                startPositionZ: 2,
                width: 25,
                height: 25,
                  collaid:"./Client/image/collaid.png",
                colliderPositionX: 0,
                colliderPositionY: 11,
                colliderPositionZ: 0,
                colliderWidth: 20,
                colliderHeight: 17,
                zIndex:1,
            },
            home4:{
                src: "./Client/image/midieval/house1.png",
                startPositionX: 20,
                startPositionY: 5,
                startPositionZ: 2,
                width: 10,
                height: 10,
                  collaid:"./Client/image/collaid.png",
                colliderPositionX: 20,
                colliderPositionY: 3,
                colliderPositionZ: 0,
                colliderWidth: 9,
                colliderHeight: 5,
                zIndex:1,
            },
            home5:{
                src: "./Client/image/midieval/house1b.png",
                startPositionX: 30,
                startPositionY: 5,
                startPositionZ: 2,
                width: 10,
                height: 10,
                  collaid:"./Client/image/collaid.png",
                colliderPositionX: 30,
                colliderPositionY: 3,
                colliderPositionZ: 0,
                colliderWidth: 9,
                colliderHeight: 5,
                zIndex:1,
            },
            home6:{
                src: "./Client/image/midieval/house1c.png",
                startPositionX: 40,
                startPositionY: 5,
                startPositionZ: 2,
                width: 10,
                height: 10,
                  collaid:"./Client/image/collaid.png",
                colliderPositionX: 40,
                colliderPositionY: 3,
                colliderPositionZ: 0,
                colliderWidth: 9,
                colliderHeight: 5,
                zIndex:1,
            },
            home7:{
                src: "./Client/image/midieval/stable.png",
                startPositionX: -14,
                startPositionY: -5,
                startPositionZ: 2,
                width: 14,
                height: 14,
                  collaid:"./Client/image/collaid.png",
                colliderPositionX: -14,
                colliderPositionY: -5,
                colliderPositionZ: 0,
                colliderWidth: 11,
                colliderHeight: 7,
                zIndex:1,
            }
            ,
            home8:{
                src: "./Client/image/midieval/blacksmith.png",
                startPositionX: 0,
                startPositionY: -15,
                startPositionZ: 2,
                width: 12,
                height: 12,
                  collaid:"./Client/image/collaid.png",
                colliderPositionX: 0,
                colliderPositionY: -15,
                colliderPositionZ: 0,
                colliderWidth: 9,
                colliderHeight: 5,
                zIndex:1,
            }*/
        }

    },
    hero: {
        src: "./Client/image/hero.png",
    }
};
