export const testMapJSON = {
    map: {
        src: "./Client/image/terrain.jpg",
        startPositionX: 0,
        startPositionY: 0,
        width: 100,
        height: 100,
        zIndex:3,
        mapSizeX: 1000,
        mapSizeY: 1000,
        mapElement:{
            home3:{
                src: "./Client/image/home.png",
                startPositionX: 0,
                startPositionY: 1,
                startPositionZ: -15,
                width: 10,
                height: 10,
                colliderPositionX: 0,
                colliderPositionY: 11,
                colliderPositionZ: 0,
                colliderWidth: 20,
                colliderHeight: 17,
                zIndex:1,
            },
            /*home:{
                src: "./Client/image/midieval/archery_range.png",
                startPositionX: 15,
                startPositionY: -10,
                startPositionZ: 2,
                width: 15,
                height: 15,
                colliderPositionX: 15,
                colliderPositionY: -10,
                colliderPositionZ: 0,
                colliderWidth: 10,
                colliderHeight: 10,
                zIndex:1,
            },
            home2:{
                src: "./Client/image/midieval/barracks.png",
                startPositionX: -20,
                startPositionY: 10,
                startPositionZ: 2,
                width: 15,
                height: 15,
                colliderPositionX: -18,
                colliderPositionY: 6,
                colliderPositionZ: 0,
                colliderWidth: 14,
                colliderHeight: 5,
                zIndex:1,
            },
            home3:{
                src: "./Client/image/midieval/castle.png",
                startPositionX: 0,
                startPositionY: 12,
                startPositionZ: 2,
                width: 25,
                height: 25,
                colliderPositionX: 0,
                colliderPositionY: 11,
                colliderPositionZ: 0,
                colliderWidth: 20,
                colliderHeight: 17,
                zIndex:1,
            },
            home4:{
                src: "./Client/image/midieval/house1.png",
                startPositionX: 20,
                startPositionY: 5,
                startPositionZ: 2,
                width: 10,
                height: 10,
                colliderPositionX: 20,
                colliderPositionY: 3,
                colliderPositionZ: 0,
                colliderWidth: 9,
                colliderHeight: 5,
                zIndex:1,
            },
            home5:{
                src: "./Client/image/midieval/house1b.png",
                startPositionX: 30,
                startPositionY: 5,
                startPositionZ: 2,
                width: 10,
                height: 10,
                colliderPositionX: 30,
                colliderPositionY: 3,
                colliderPositionZ: 0,
                colliderWidth: 9,
                colliderHeight: 5,
                zIndex:1,
            },
            home6:{
                src: "./Client/image/midieval/house1c.png",
                startPositionX: 40,
                startPositionY: 5,
                startPositionZ: 2,
                width: 10,
                height: 10,
                colliderPositionX: 40,
                colliderPositionY: 3,
                colliderPositionZ: 0,
                colliderWidth: 9,
                colliderHeight: 5,
                zIndex:1,
            },
            home7:{
                src: "./Client/image/midieval/stable.png",
                startPositionX: -14,
                startPositionY: -5,
                startPositionZ: 2,
                width: 14,
                height: 14,
                colliderPositionX: -14,
                colliderPositionY: -5,
                colliderPositionZ: 0,
                colliderWidth: 11,
                colliderHeight: 7,
                zIndex:1,
            }
            ,
            home8:{
                src: "./Client/image/midieval/blacksmith.png",
                startPositionX: 0,
                startPositionY: -15,
                startPositionZ: 2,
                width: 12,
                height: 12,
                colliderPositionX: 0,
                colliderPositionY: -15,
                colliderPositionZ: 0,
                colliderWidth: 9,
                colliderHeight: 5,
                zIndex:1,
            }*/
        }

    },
  hero:{
      src: "./Client/image/hero.png",
  }
};
