export const testMapJSON = {
    map: {
        src: "./Client/image/testRepeatGround.png",
        startPositionX: 0,
        startPositionY: 0,
        width: 100,
        height: 100,
        zIndex: 3,
        mapSizeX: 1000,
        mapSizeY: 1000,
        mapElement: {
            home1: {
                src: "./Client/image/home.png",
                startPositionX: 10,
                startPositionY: 0,
                startPositionZ: 10,
                width: 10,
                height: 10,
                collaid: "./Client/image/collaid.png",
                colliderPositionX: 7,
                colliderPositionY: 2,
                colliderPositionZ: 3,
                colliderWidth: 10,
                colliderHeight:10,
                colliderLength:3,
                zIndex: 1,
            },
            tree1: {
                src: "./Client/image/treeTest.png",
                startPositionX: -5,
                startPositionY: 0,
                startPositionZ: -5,
                width: 3,
                height: 3,
                collaid: "./Client/image/collaid.png",
                colliderPositionX: -5,
                colliderPositionY: 2,
                colliderPositionZ: 0,
                colliderWidth: 3,
                colliderHeight:10,
                colliderLength:10,
                zIndex: 1,
            },
        /*    tree2: {
                src: "./Client/image/treeTest.png",
                startPositionX: 0,
                startPositionY: 0,
                startPositionZ: -8,
                width: 5,
                height: 5,
                collaid: "./Client/image/collaid.png",
                colliderPositionX: 0,
                colliderPositionY: 0.01,
                colliderPositionZ: -8,
                colliderWidth: 0.5,
                colliderHeight: 0.5,
                zIndex: 1,
            },
*/
        }

    },
    player: {
        src: "./Client/image/Player_v0.0.3.png",
        collaid:"./Client/image/collaid.png",
        colliderPositionX: 0,
        colliderPositionY: 0,
        colliderPositionZ: 0,
        colliderWidth: 1,
        colliderHeight: 1,
        health:100,
        damage:1,
        attackDistance:1,
        attackSpeed:10
    },
    enemy: {
        src: "./Client/image/hero.png",
        collaid:"./Client/image/collaid.png",
        scope:"./Client/image/persecutionRadius.png",
        scopeRadius:16,

        colliderPosition:{
            x: 0,
            y: 0.01,
            z: 0,
        },
        colliderWidth: 1,
        colliderHeight: 1,
        pursuitZone:20,
        persecutionRadius:"./Client/image/persecutionRadius.png",
        health:100,
        damage:1,
        attackDistance:1,
        attackSpeed:10
    }
};
