export const MapJSON = {
//Числа должны быть кратны двум иначе будет построено на одну дополнительную точку больше
    map: {
        src: "./Client/image/terrain_snow.jpg",
        startPositionX: 0,
        startPositionY: 0,
        width: 100,
        height: 0,
        length: 100,
        zIndex: 3,
        mapSizeX: 1000,
        mapSizeY: 1000,
        // mapElement: {},
        mapElement: {
            // home1: {
            //     src: "./Client/image/home.png",
            //     startPositionX: 0,
            //     startPositionY: 0,
            //     startPositionZ: 0,
            //     width: 10,
            //     height: 10,
            //     collaid: "./Client/image/collaid.png",
            //     colliderPositionX: 3,
            //     colliderPositionY: 0,
            //     colliderPositionZ: 0,
            //     colliderWidth: 2,
            //     colliderHeight: 1,
            //     colliderLength: 2,
            //     zIndex: 1,
            // },
            // home2: {
            //     src: "./Client/image/home.png",
            //     startPositionX: 0,
            //     startPositionY: 0,
            //     startPositionZ: 0,
            //     width: 10,
            //     height: 10,
            //     collaid: "./Client/image/collaid.png",
            //     colliderPositionX: -4,
            //     colliderPositionY: 0,
            //     colliderPositionZ: 0,
            //     colliderWidth: 2,
            //     colliderHeight: 1,
            //     colliderLength: 2,
            //     zIndex: 1,
            // },
            wall_1: {
                src: null,
                startPositionX: 0,
                startPositionY: 0,
                startPositionZ: 0,
                width: 3,
                height: 3,
                collaidTexture: "./Client/image/wall.jpg",
                colliderPositionX: 10,
                colliderPositionY: 0,
                colliderPositionZ: -10,
                colliderWidth: 8,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
                dimensional:true,
            },
            wall_2: {
                src: null,
                startPositionX: 0,
                startPositionY: 0,
                startPositionZ: 0,
                width: 3,
                height: 3,
                collaidTexture: "./Client/image/wall.jpg",
                colliderPositionX: -10,
                colliderPositionY: 0,
                colliderPositionZ: -10,
                colliderWidth: 8,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
                dimensional:true,
            },
            wall_3: {
                src: null,
                startPositionX: 0,
                startPositionY: 0,
                startPositionZ: 0,
                width: 6,
                height: 6,
                collaidTexture: "./Client/image/wall.jpg",
                colliderPositionX: 0,
                colliderPositionY: 0,
                colliderPositionZ: 10,
                colliderWidth: 20,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
                dimensional:true,
            },
            wall_4: {
                src: null,
                startPositionX: 0,
                startPositionY: 0,
                startPositionZ: 0,
                width: 6,
                height: 6,
                collaidTexture: "./Client/image/wall.jpg",
                colliderPositionX: -16,
                colliderPositionY: 0,
                colliderPositionZ: 0,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 16,
                zIndex: 1,
                dimensional:true,
            },
            wall_5: {
                src: null,
                startPositionX: 0,
                startPositionY: 0,
                startPositionZ: 0,
                width: 6,
                height: 6,
                collaidTexture: "./Client/image/wall.jpg",
                colliderPositionX: 16,
                colliderPositionY: 0,
                colliderPositionZ: 0,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 16,
                zIndex: 1,
                dimensional:true,
            },
            tree_left_top_1: {
                src: "./Client/image/treeTest.png",
                startPositionX: -23,
                startPositionY: 1.5,
                startPositionZ: -9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -23,
                colliderPositionY: 0,
                colliderPositionZ: -5.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_2: {
                src: "./Client/image/treeTest.png",
                startPositionX: -33,
                startPositionY: 1.5,
                startPositionZ: -9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -33,
                colliderPositionY: 0,
                colliderPositionZ: -5.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_3: {
                src: "./Client/image/treeTest.png",
                startPositionX: -43,
                startPositionY: 1.5,
                startPositionZ: -9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -43,
                colliderPositionY: 0,
                colliderPositionZ: -5.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_4: {
                src: "./Client/image/treeTest.png",
                startPositionX: -20,
                startPositionY: 1.5,
                startPositionZ: -3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -20,
                colliderPositionY: 0,
                colliderPositionZ: 0.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_5: {
                src: "./Client/image/treeTest.png",
                startPositionX: -30,
                startPositionY: 1.5,
                startPositionZ: -3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -30,
                colliderPositionY: 0,
                colliderPositionZ: 0.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_6: {
                src: "./Client/image/treeTest.png",
                startPositionX: -40,
                startPositionY: 1.5,
                startPositionZ: -3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -40,
                colliderPositionY: 0,
                colliderPositionZ: 0.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_7: {
                src: "./Client/image/treeTest.png",
                startPositionX: -23,
                startPositionY: 1.5,
                startPositionZ: 3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -23,
                colliderPositionY: 0,
                colliderPositionZ: 6.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_8: {
                src: "./Client/image/treeTest.png",
                startPositionX: -33,
                startPositionY: 1.5,
                startPositionZ: 3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -33,
                colliderPositionY: 0,
                colliderPositionZ: 6.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_9: {
                src: "./Client/image/treeTest.png",
                startPositionX: -43,
                startPositionY: 1.5,
                startPositionZ: 3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -43,
                colliderPositionY: 0,
                colliderPositionZ: 6.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_10: {
                src: "./Client/image/treeTest.png",
                startPositionX: -20,
                startPositionY: 1.5,
                startPositionZ: 9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -20,
                colliderPositionY: 0,
                colliderPositionZ: 12.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_11: {
                src: "./Client/image/treeTest.png",
                startPositionX: -30,
                startPositionY: 1.5,
                startPositionZ: 9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -30,
                colliderPositionY: 0,
                colliderPositionZ: 12.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_12: {
                src: "./Client/image/treeTest.png",
                startPositionX: -40,
                startPositionY: 1.5,
                startPositionZ: 9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -40,
                colliderPositionY: 0,
                colliderPositionZ: 12.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_13: {
                src: "./Client/image/treeTest.png",
                startPositionX: -23,
                startPositionY: 1.5,
                startPositionZ: 15,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -23,
                colliderPositionY: 0,
                colliderPositionZ: 18.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_14: {
                src: "./Client/image/treeTest.png",
                startPositionX: -33,
                startPositionY: 1.5,
                startPositionZ: 15,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -33,
                colliderPositionY: 0,
                colliderPositionZ: 18.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_left_top_15: {
                src: "./Client/image/treeTest.png",
                startPositionX: -43,
                startPositionY: 1.5,
                startPositionZ: 15,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -43,
                colliderPositionY: 0,
                colliderPositionZ: 18.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_1: {
                src: "./Client/image/treeTest.png",
                startPositionX: 23,
                startPositionY: 1.5,
                startPositionZ: -9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 23,
                colliderPositionY: 0,
                colliderPositionZ: -5.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_2: {
                src: "./Client/image/treeTest.png",
                startPositionX: 33,
                startPositionY: 1.5,
                startPositionZ: -9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 33,
                colliderPositionY: 0,
                colliderPositionZ: -5.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_3: {
                src: "./Client/image/treeTest.png",
                startPositionX: 43,
                startPositionY: 1.5,
                startPositionZ: -9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 43,
                colliderPositionY: 0,
                colliderPositionZ: -5.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_4: {
                src: "./Client/image/treeTest.png",
                startPositionX: 20,
                startPositionY: 1.5,
                startPositionZ: -3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 20,
                colliderPositionY: 0,
                colliderPositionZ: 0.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_5: {
                src: "./Client/image/treeTest.png",
                startPositionX: 30,
                startPositionY: 1.5,
                startPositionZ: -3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 30,
                colliderPositionY: 0,
                colliderPositionZ: 0.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_6: {
                src: "./Client/image/treeTest.png",
                startPositionX: 40,
                startPositionY: 1.5,
                startPositionZ: -3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 40,
                colliderPositionY: 0,
                colliderPositionZ: 0.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_7: {
                src: "./Client/image/treeTest.png",
                startPositionX: 23,
                startPositionY: 1.5,
                startPositionZ: 3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 23,
                colliderPositionY: 0,
                colliderPositionZ: 6.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_8: {
                src: "./Client/image/treeTest.png",
                startPositionX: 33,
                startPositionY: 1.5,
                startPositionZ: 3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 33,
                colliderPositionY: 0,
                colliderPositionZ: 6.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_9: {
                src: "./Client/image/treeTest.png",
                startPositionX: 43,
                startPositionY: 1.5,
                startPositionZ: 3,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 43,
                colliderPositionY: 0,
                colliderPositionZ: 6.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_10: {
                src: "./Client/image/treeTest.png",
                startPositionX: 20,
                startPositionY: 1.5,
                startPositionZ: 9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 20,
                colliderPositionY: 0,
                colliderPositionZ: 12.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_11: {
                src: "./Client/image/treeTest.png",
                startPositionX: 30,
                startPositionY: 1.5,
                startPositionZ: 9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 30,
                colliderPositionY: 0,
                colliderPositionZ: 12.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_12: {
                src: "./Client/image/treeTest.png",
                startPositionX: 40,
                startPositionY: 1.5,
                startPositionZ: 9,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 40,
                colliderPositionY: 0,
                colliderPositionZ: 12.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_13: {
                src: "./Client/image/treeTest.png",
                startPositionX: 23,
                startPositionY: 1.5,
                startPositionZ: 15,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 23,
                colliderPositionY: 0,
                colliderPositionZ: 18.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_14: {
                src: "./Client/image/treeTest.png",
                startPositionX: 33,
                startPositionY: 1.5,
                startPositionZ: 15,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 33,
                colliderPositionY: 0,
                colliderPositionZ: 18.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            tree_right_top_15: {
                src: "./Client/image/treeTest.png",
                startPositionX: 43,
                startPositionY: 1.5,
                startPositionZ: 15,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 43,
                colliderPositionY: 0,
                colliderPositionZ: 18.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            stone_down_1: {
                src: "./Client/image/stone.png",
                startPositionX: -10,
                startPositionY: 0.8,
                startPositionZ: 20,
                width: 5,
                height: 5,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -10,
                colliderPositionY: 0,
                colliderPositionZ:20,
                colliderWidth: 3,
                colliderHeight: 1,
                colliderLength: 3,
                zIndex: 1,
            },
            stone_down_2: {
                src: "./Client/image/stone.png",
                startPositionX: -5,
                startPositionY: 0.8,
                startPositionZ: 15,
                width: 5,
                height: 5,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -5,
                colliderPositionY: 0,
                colliderPositionZ: 15,
                colliderWidth: 3,
                colliderHeight: 1,
                colliderLength: 3,
                zIndex: 1,
            },
            tree_down_2: {
                src: "./Client/image/treeTest.png",
                startPositionX: 0,
                startPositionY: 1.5,
                startPositionZ: 12,
                width: 10,
                height: 10,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 0,
                colliderPositionY: 0,
                colliderPositionZ: 15.5,
                colliderWidth: 2,
                colliderHeight: 1,
                colliderLength: 2,
                zIndex: 1,
            },
            stone_down_3: {
                src: "./Client/image/stone.png",
                startPositionX: 0,
                startPositionY: 0.8,
                startPositionZ: 20,
                width: 5,
                height: 5,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 0,
                colliderPositionY: 0,
                colliderPositionZ: 20,
                colliderWidth: 3,
                colliderHeight: 1,
                colliderLength: 3,
                zIndex: 1,
            },
            stone_down_4: {
                src: "./Client/image/stone.png",
                startPositionX: 5,
                startPositionY: 0.8,
                startPositionZ: 15,
                width: 5,
                height: 5,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 5,
                colliderPositionY: 0,
                colliderPositionZ: 15,
                colliderWidth: 3,
                colliderHeight: 1,
                colliderLength: 3,
                zIndex: 1,
            },
            stone_down_5: {
                src: "./Client/image/stone.png",
                startPositionX: 10,
                startPositionY: 0.8,
                startPositionZ: 20,
                width: 5,
                height: 5,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: 10,
                colliderPositionY: 0,
                colliderPositionZ: 20,
                colliderWidth: 3,
                colliderHeight: 1,
                colliderLength: 3,
                zIndex: 1,
            },
            home_1: {
                src: "./Client/image/home.png",
                startPositionX: 0,
                startPositionY: 1.5,
                startPositionZ: -23,
                width: 15,
                height: 15,
                collaidTexture: "./Client/image/collaid.png",
                colliderPositionX: -2,
                colliderPositionY: 0,
                colliderPositionZ: -23,
                colliderWidth: 12,
                colliderHeight: 1,
                colliderLength: 10,
                zIndex: 1,
            },
        },
        enemyOnMap: [
            {
                typeEnemy: 'enemy1',
                count: 5,
                startPoint: {x: 20, y: 0, z: 20},
                distanceBetweenEnemies: 1
            },
            {
                typeEnemy: 'enemy2',
                count: 5,
                startPoint: {x: 20, y: 0, z: -20},
                distanceBetweenEnemies: 2
            },
            {
                typeEnemy: 'enemy3',
                count: 0,
                startPoint: {x: -20, y: 0, z: -20},
                distanceBetweenEnemies: 0.5
            },
            {
                typeEnemy: 'enemy4',
                count: 0,
                startPoint: {x: -20, y: 0, z: 20},
                distanceBetweenEnemies: 0.5
            },
        ]

    },

};
