export const PlayerJson = {
    123: {
        src: "./Client/image/spriteTest.png",
		numberOfFramesX:8,
		numberOfFramesY:8,
		firstFrameMove:1,
		lastFrameMove:8,
		firstFrameAttack:null,
		lastFrameAttack :null,
		firstFrameDeath:null,
		lastFrameDeath:null,
        collaid:"./Client/image/collaid.png",
        colliderPositionX: 0,
        colliderPositionY: 0,
        colliderPositionZ: 0,
        colliderWidth: 1,
        colliderHeight: 2,
        colliderLength:1,
        health:100,
        damage:2,
        attackDistance:1,
        attackSpeed:10,
        moveSpeed:1
    },
    1: {
        src: "./Client/image/Player_v0.0.4.png",
        collaid:"./Client/image/collaid.png",
        colliderPositionX: 0,
        colliderPositionY: 0,
        colliderPositionZ: 0,
        colliderWidth: 1,
        colliderHeight: 2,
        colliderLength:1,
        health:100,
        damage:2,
        attackDistance:1,
        attackSpeed:10,
        moveSpeed:1
    },
    2: {
        src: "./Client/image/Player_v0.0.4.png",
        collaid:"./Client/image/collaid.png",
        colliderPositionX: 0,
        colliderPositionY: 0,
        colliderPositionZ: 0,
        colliderWidth: 1,
        colliderHeight: 2,
        colliderLength:1,
        health:100,
        damage:2,
        attackDistance:1,
        attackSpeed:10,
        moveSpeed:1
    },
    3: {
        src: "./Client/image/Player_v0.0.4.png",
        collaid:"./Client/image/collaid.png",
        colliderPositionX: 0,
        colliderPositionY: 0,
        colliderPositionZ: 0,
        colliderWidth: 1,
        colliderHeight: 2,
        colliderLength:1,
        health:100,
        damage:2,
        attackDistance:1,
        attackSpeed:10,
        moveSpeed:1
    },
    4: {
        src: "./Client/image/Player_v0.0.4.png",
        collaid:"./Client/image/collaid.png",
        colliderPositionX: 0,
        colliderPositionY: 0,
        colliderPositionZ: 0,
        colliderWidth: 1,
        colliderHeight: 2,
        colliderLength:1,
        health:100,
        damage:2,
        attackDistance:1,
        attackSpeed:10,
        moveSpeed:1
    },
    5: {
        src: "./Client/image/Player_v0.0.4.png",
        collaid:"./Client/image/collaid.png",
        colliderPositionX: 0,
        colliderPositionY: 0,
        colliderPositionZ: 0,
        colliderWidth: 1,
        colliderHeight: 2,
        colliderLength:1,
        health:100,
        damage:2,
        attackDistance:1,
        attackSpeed:10,
        moveSpeed:1
    },
};
