import * as THREE from "three";

export const PlayerJson = {
	123: {
		sprite:{
			src: "./Client/image/Player_v0_0_4.png",
			numberOfFramesX: 17,
			numberOfFramesY: 14,
			firstFrameMove: 2,
			lastFrameMove: 9,
			frameMoveUp: 1,
			frameMoveUpRight: 3,
			frameMoveUpLeft: 31,

			frameMoveDown: 17,
			frameMoveDownRight: 14,
			frameMoveDownLeft: 20,
			//Нам нужен реверс кадра в клиенте у нас выставленна опция THREE.MirroredRepeatWrapping которая делает зеркальное отражения и нам просто нужно посчитать номер кадра по зеркалу
			frameMoveLeft: 27,
			frameMoveRight: 9,
			firstFrameAttack: 10,
			lastFrameAttack: 11,
			firstFrameDeath: null,
			lastFrameDeath: null,
		},
		collaid: "./Client/image/collaid.png",
		colliderPositionX: 0,
		colliderPositionY: 0,
		colliderPositionZ: 0,
		colliderWidth: 1,
		colliderHeight: 2,
		colliderLength: 1,
		health: 100,
		damage: 2,
		attackDistance: 1,
		attackSpeed: 10,
		moveSpeed: 1
	},
	1: {
		sprite:{
			src: "./Client/image/Player_v0_0_4.png",
			numberOfFramesX: 17,
			numberOfFramesY: 14,
			firstFrameMove: 2,
			lastFrameMove: 9,
			frameMoveUp: 1,
			frameMoveUpRight: 3,
			frameMoveUpLeft: 31,

			frameMoveDown: 17,
			frameMoveDownRight: 14,
			frameMoveDownLeft: 20,
			//Нам нужен реверс кадра в клиенте у нас выставленна опция THREE.MirroredRepeatWrapping которая делает зеркальное отражения и нам просто нужно посчитать номер кадра по зеркалу
			frameMoveLeft: 27,
			frameMoveRight: 9,
			firstFrameAttack: 10,
			lastFrameAttack: 11,
			firstFrameDeath: null,
			lastFrameDeath: null,
		},
		collaid: "./Client/image/collaid.png",
		colliderPositionX: 0,
		colliderPositionY: 0,
		colliderPositionZ: 0,
		colliderWidth: 1,
		colliderHeight: 2,
		colliderLength: 1,
		health: 100,
		damage: 2,
		attackDistance: 1,
		attackSpeed: 10,
		moveSpeed: 1
	},
	2: {
		sprite:{
			src: "./Client/image/Player_v0_0_4.png",
			numberOfFramesX: 17,
			numberOfFramesY: 14,
			firstFrameMove: 2,
			lastFrameMove: 9,
			frameMoveUp: 1,
			frameMoveDown: 17,
			//Нам нужен реверс кадра в клиенте у нас выставленна опция THREE.MirroredRepeatWrapping которая делает зеркальное отражения и нам просто нужно посчитать номер кадра по зеркалу
			frameMoveLeft: 27,
			frameMoveRight: 9,
			firstFrameAttack: 10,
			lastFrameAttack: 11,
			firstFrameDeath: null,
			lastFrameDeath: null,
		},
		collaid: "./Client/image/collaid.png",
		colliderPositionX: 0,
		colliderPositionY: 0,
		colliderPositionZ: 0,
		colliderWidth: 1,
		colliderHeight: 2,
		colliderLength: 1,
		health: 100,
		damage: 2,
		attackDistance: 1,
		attackSpeed: 10,
		moveSpeed: 1
	},
	3: {
		src: "./Client/image/Player_v0.0.4.png",
		collaid: "./Client/image/collaid.png",
		colliderPositionX: 0,
		colliderPositionY: 0,
		colliderPositionZ: 0,
		colliderWidth: 1,
		colliderHeight: 2,
		colliderLength: 1,
		health: 100,
		damage: 2,
		attackDistance: 1,
		attackSpeed: 10,
		moveSpeed: 1
	},
	4: {
		src: "./Client/image/Player_v0.0.4.png",
		collaid: "./Client/image/collaid.png",
		colliderPositionX: 0,
		colliderPositionY: 0,
		colliderPositionZ: 0,
		colliderWidth: 1,
		colliderHeight: 2,
		colliderLength: 1,
		health: 100,
		damage: 2,
		attackDistance: 1,
		attackSpeed: 10,
		moveSpeed: 1
	},
	5: {
		src: "./Client/image/Player_v0.0.4.png",
		collaid: "./Client/image/collaid.png",
		colliderPositionX: 0,
		colliderPositionY: 0,
		colliderPositionZ: 0,
		colliderWidth: 1,
		colliderHeight: 2,
		colliderLength: 1,
		health: 100,
		damage: 2,
		attackDistance: 1,
		attackSpeed: 10,
		moveSpeed: 1
	},
};
